/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteImport } from './routes/static'
import { Route as OpenUiRouteImport } from './routes/open-ui'
import { Route as OpenEndedRouteImport } from './routes/open-ended'
import { Route as DeclarativeRouteImport } from './routes/declarative'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const StaticRoute = StaticRouteImport.update({
  id: '/static',
  path: '/static',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenUiRoute = OpenUiRouteImport.update({
  id: '/open-ui',
  path: '/open-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenEndedRoute = OpenEndedRouteImport.update({
  id: '/open-ended',
  path: '/open-ended',
  getParentRoute: () => rootRouteImport,
} as any)
const DeclarativeRoute = DeclarativeRouteImport.update({
  id: '/declarative',
  path: '/declarative',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/declarative': typeof DeclarativeRoute
  '/open-ended': typeof OpenEndedRoute
  '/open-ui': typeof OpenUiRoute
  '/static': typeof StaticRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/declarative': typeof DeclarativeRoute
  '/open-ended': typeof OpenEndedRoute
  '/open-ui': typeof OpenUiRoute
  '/static': typeof StaticRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/declarative': typeof DeclarativeRoute
  '/open-ended': typeof OpenEndedRoute
  '/open-ui': typeof OpenUiRoute
  '/static': typeof StaticRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/declarative'
    | '/open-ended'
    | '/open-ui'
    | '/static'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/declarative'
    | '/open-ended'
    | '/open-ui'
    | '/static'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/declarative'
    | '/open-ended'
    | '/open-ui'
    | '/static'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeclarativeRoute: typeof DeclarativeRoute
  OpenEndedRoute: typeof OpenEndedRoute
  OpenUiRoute: typeof OpenUiRoute
  StaticRoute: typeof StaticRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/static': {
      id: '/static'
      path: '/static'
      fullPath: '/static'
      preLoaderRoute: typeof StaticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-ui': {
      id: '/open-ui'
      path: '/open-ui'
      fullPath: '/open-ui'
      preLoaderRoute: typeof OpenUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-ended': {
      id: '/open-ended'
      path: '/open-ended'
      fullPath: '/open-ended'
      preLoaderRoute: typeof OpenEndedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/declarative': {
      id: '/declarative'
      path: '/declarative'
      fullPath: '/declarative'
      preLoaderRoute: typeof DeclarativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeclarativeRoute: DeclarativeRoute,
  OpenEndedRoute: OpenEndedRoute,
  OpenUiRoute: OpenUiRoute,
  StaticRoute: StaticRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
